const express = require('express');
const router = express.Router();
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const nodemailer = require('nodemailer');

// Create email transporter
const createTransporter = () => {
    return nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 587,
        secure: false,
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS
        },
        tls: { rejectUnauthorized: false }
    });
};

// @route   POST /api/password/forgot
// @desc    Send password reset email
router.post('/forgot', async (req, res) => {
    try {
        const { email } = req.body;

        if (!email) {
            return res.status(400).json({
                success: false,
                message: 'Please provide your email'
            });
        }

        // Find user
        const user = await User.findOne({ email });
        if (!user) {
            return res.status(404).json({
                success: false,
                message: 'No account found with this email'
            });
        }

        // Check if Google account
        if (user.googleId) {
            return res.status(400).json({
                success: false,
                message: 'This account uses Google login. Please sign in with Google.'
            });
        }

        // Generate reset token
        const resetToken = crypto.randomBytes(32).toString('hex');
        const hashedToken = crypto
            .createHash('sha256')
            .update(resetToken)
            .digest('hex');

        // Save token to user
        user.resetPasswordToken = hashedToken;
        user.resetPasswordExpire = Date.now() + 30 * 60 * 1000; // 30 minutes
        await user.save();

        // Create reset URL
        const baseUrl = process.env.NODE_ENV === 'production'
            ? 'https://resume-analyzer-7y62.onrender.com'
            : 'http://localhost:5000';

        const resetUrl = `${baseUrl}/reset-password.html?token=${resetToken}&email=${email}`;

        // Send email
        const transporter = createTransporter();

        const htmlContent = `
<!DOCTYPE html>
<html>
<body style="font-family:'Segoe UI',sans-serif;background:#f0f0ff;padding:20px;margin:0;">
<div style="max-width:500px;margin:0 auto;">

  <div style="background:linear-gradient(135deg,#6c63ff,#f50057);border-radius:16px;padding:32px;text-align:center;margin-bottom:20px;">
    <div style="font-size:40px;">🧠</div>
    <h1 style="color:white;margin:8px 0 0;font-size:22px;">Resume Analyzer</h1>
    <p style="color:rgba(255,255,255,0.85);margin:6px 0 0;font-size:14px;">Password Reset Request</p>
  </div>

  <div style="background:white;border-radius:12px;padding:28px;margin-bottom:16px;">
    <h2 style="color:#1a1a2e;font-size:18px;margin:0 0 12px;">Hi ${user.name}! 👋</h2>
    <p style="color:#555570;font-size:14px;line-height:1.6;margin:0 0 20px;">
      We received a request to reset your password. Click the button below to create a new password.
      This link will expire in <strong>30 minutes</strong>.
    </p>
    <div style="text-align:center;margin:24px 0;">
      <a href="${resetUrl}"
        style="background:linear-gradient(135deg,#6c63ff,#f50057);color:white;text-decoration:none;padding:14px 32px;border-radius:8px;font-size:15px;font-weight:700;display:inline-block;">
        🔐 Reset My Password
      </a>
    </div>
    <p style="color:#999;font-size:12px;text-align:center;margin:16px 0 0;">
      If you did not request this, please ignore this email. Your password will remain unchanged.
    </p>
  </div>

  <div style="text-align:center;font-size:12px;color:#999;">
    Generated by <strong style="color:#6c63ff;">Resume Analyzer AI</strong>
  </div>
</div>
</body>
</html>`;

        await transporter.sendMail({
            from: `"Resume Analyzer" <${process.env.EMAIL_USER}>`,
            to: email,
            subject: '🔐 Reset Your Resume Analyzer Password',
            html: htmlContent
        });

        res.status(200).json({
            success: true,
            message: `Password reset link sent to ${email}`
        });

    } catch (error) {
        console.error('Forgot Password Error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to send reset email: ' + error.message
        });
    }
});

// @route   POST /api/password/reset
// @desc    Reset password with token
router.post('/reset', async (req, res) => {
    try {
        const { token, email, password } = req.body;

        if (!token || !email || !password) {
            return res.status(400).json({
                success: false,
                message: 'All fields are required'
            });
        }

        if (password.length < 6) {
            return res.status(400).json({
                success: false,
                message: 'Password must be at least 6 characters'
            });
        }

        // Hash token to compare
        const hashedToken = crypto
            .createHash('sha256')
            .update(token)
            .digest('hex');

        // Find user with valid token
        const user = await User.findOne({
            email,
            resetPasswordToken: hashedToken,
            resetPasswordExpire: { $gt: Date.now() }
        });

        if (!user) {
            return res.status(400).json({
                success: false,
                message: 'Invalid or expired reset link. Please request a new one.'
            });
        }

        // Hash new password
        const salt = await bcrypt.genSalt(10);
        user.password = await bcrypt.hash(password, salt);
        user.resetPasswordToken = null;
        user.resetPasswordExpire = null;
        await user.save();

        res.status(200).json({
            success: true,
            message: 'Password reset successfully! You can now login.'
        });

    } catch (error) {
        console.error('Reset Password Error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to reset password: ' + error.message
        });
    }
});

module.exports = router;